### ISSUE TITLE
No Twitter login due to REST API v1 is no longer active

### ISSUE THREAD

**Issue by joland** [opauth/opauth#107]
[error] => Array
        (
            [provider] => Twitter
            [code] => 410
            [raw] => {"errors":[{"message":"The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.","code":64}]}
        )

    [timestamp] => 2015-01-20T15:13:37+01:00

Ps. i just downloaded it and gave it a whirl. But out of the box returning 404?

**Comment by ceeram** [comment]
That is an issue of opauth/twitter, although current master does use api
v1.1, looks like you used an incorrect version of opauth/twitter

2015-01-20 15:19 GMT+01:00 joland <notifications@github.com>:
