### ISSUE TITLE
Symfony2 support?

### ISSUE THREAD

**Issue by clemblanco** [opauth/opauth#15]
Hey guys!

When do you think you'll fully support Symfony2 framework? :)

Best wishes.

**Comment by nashfx** [comment]
@Claymm I know this was closed a long time ago but I'm having the same issue with the response and the int_callback function. How did you solved this?

**Comment by Claymm** [comment]
Sorry guys I haven't done any Symfony2 work for ages. I'm using Laravel now and I can't even remember me commenting here :/ I think that bundle never got finalised.

**Comment by nashfx** [comment]
@Claymm I'm actually trying to use this in Laravel and facing the same issue that your had
